---
title: "Checking fitters and variance estimators"
author: "B"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dependencies.
```{r}
library(robustbase)
source("../../R/functions.r")
source("../../R/ddsandwich.R")
```

## Simulation

Simulation parameters: number of sims; seed.
```{r}

if (!exists('nreps') ) nreps <- 3
nreps
set.seed(201609)

```

Scenarios to simulate: sample sizes, bandwidth.

```{r}
( nsample = c(5e1, 5e2, 5e3) )
BW = 0.3
```

Simulated coefficients, SEs and pvals
```{r, warning=FALSE}
sims = list()
simwarnings = list()
for (ns in nsample)
    {
sims[[as.character(ns)]] = 
  replicate(nreps, {
  ctl <- lmrob.control(k.max=500,maxit.scale=500)
  dat = makeData(ns,curve=0,tdist=T,tau=0)
  dat = subset(dat, abs(R)<BW)
  fit = lmrob(Y~Z+R, data=dat,method='MM',control=ctl)
  fit$cov <- .vcov.avar2(fit)
  zpos = pmatch('Z', names(coef(fit)))
  coef(summary(fit))[zpos,]
})
simwarnings[[as.character(ns)]] <-
    if (exists('last.warning')) last.warning else NULL
}
```

Sizes of the tests.
```{r}
sapply(sims, 
  function(simres) prop.test(sum(simres["Pr(>|t|)",] <=.05, na.rm=T), 
                             sum(!is.na( simres["Pr(>|t|)",] )), 
                            p=.05)
)
```
Are the coefficient estimates biased?  How much?
```{r}
sapply(sims, 
       function(simres) t.test(simres["Estimate",]))
```

How about the variance estimate?

```{r}
sims.V =
  sapply(sims, 
       function(simres) 
       {
         zbar = mean(simres["Estimate",])
         zbar.m2 =var(simres["Estimate",])
         zbar.m4 = mean( ((simres["Estimate",]) - zbar)^4 )
           v.simSE = (zbar.m4 - zbar.m2^2)/sqrt(ncol(simres)) 
           vhatbar = mean(simres['Std. Error',]^2)
           vhatbarSE = sd(simres['Std. Error',]^2)/sqrt(ncol(simres))
           c(v.sim=zbar.m2, v.simSE=v.simSE, 
             vhatbar=vhatbar, vhatbarSE=vhatbarSE)
       }
         )

sims.V       
```

### Session details

```{r}
sessionInfo()
save(sims, simwarnings, sims.V, file="check-sh-deps.RData")
```
